### PR TITLE
Add note to readme for npm@7 users

### PR DESCRIPTION
**Pull request by t1m0thyj**
Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
LGTM!
Question, Don't we need to surface that prereq somewhere on Zowe DocsSite?

**Comment by zFernand0** [comment]
As per discussed in standup, we may want to make a similar note in the link below for people using NPM v7
https://docs.zowe.org/stable/user-guide/cli-scsplugin.html#software-requirements

**Review by MichaelABroadcom — APPROVED** [review]
Reviewed and approved.

**Comment by zFernand0** [comment]
Please see https://github.com/zowe/docs-site/issues/1569 to follow up on the Docs-Site update 😋

**Pull request merged**
